service: serverless-typescript-worker
frameworkVersion: '2 || 3'

plugins:
  - serverless-lift
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

constructs:
  jobs:
    type: queue
    fifo: true
    worker:
      handler: index.consumer
    extensions:
      queue:
        Properties:
          QueueName: 'QUEUE_NAME'
      dlq:
        Properties:
          QueueName: 'QUEUE_NAME-dlq'
